#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/@
thepenchantit permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404.html;' /etc/nginx/sites-available/default
service nginx restart
