#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

apt-get update -y
apt-get install nginx -y

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
		listen 80;
		listen [::]:80 default_server;
		add_header X-Served-By $HOSTNAME;

		root /var/www/html;
		index index.html index.htm;

		location /redirect_me {
			return 301 http://cuberule.com/;
		}

		error_page 404 /404.html;
		location = /404.html {
			root /etc/nginx/html;
			internal;
		}
}" > /etc/nginx/sites-available/default

service nginx restart
