#!/usr/bin/env bash
#install load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend thepenchantit
	bind *:80
	mode http
	default_backend app

backend app
    balance roundrobin
    server 134922-web-01 100.25.162.53:80 check
    server 134922-web-02 54.237.35.12:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
