#!/usr/bin/env bash
# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Assign the first argument to a variable
IP_ADDRESS=$1

# Ping the IP address 5 times
ping -c 5 $IP_ADDRESS
